// Package these two dependency-free modules as one classic browser script.
// A classic script can run from file:// without disabling browser security.
import { readFileSync, writeFileSync } from 'node:fs';
import { Script } from 'node:vm';

const source = name => readFileSync(new URL(name, import.meta.url), 'utf8');
const data = source('data.mjs').replace(/^export (?=(?:const|function)\b)/gm, '');
const app = source('app.mjs').replace(/^import \{[^}]+\} from '\.\/data\.mjs';\r?\n/, '');
if (/^\s*(?:import|export)\s/m.test(data + '\n' + app)) {
  throw new Error('Unsupported module syntax. Update the bundler before adding imports or exports.');
}
const bundle = '// Generated by node build.mjs. Edit data.mjs and app.mjs, then rebuild.\n' +
  "(() => {\n'use strict';\n\n" + data + '\n' + app + '\n})();\n';
new Script(bundle, { filename: 'app.bundle.js' });
if (process.argv.includes('--check')) {
  if (source('app.bundle.js') !== bundle) throw new Error('app.bundle.js is stale. Run node build.mjs.');
  console.log('PASS: browser bundle matches source modules.');
} else {
  writeFileSync(new URL('app.bundle.js', import.meta.url), bundle);
  console.log('Built app.bundle.js for file:// and HTTP.');
}
